analytics: {}
color:
  brandColors:
    - '#2c1f31'
    - '#b2926c'
    - '#604c45'
    - '#8e6b4b'
    - '#e9cd9c'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0
name: 'Ernie '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0
