name: 'Ernie '
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Ernie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c1f31'
    - '#b2926c'
    - '#604c45'
    - '#8e6b4b'
    - '#e9cd9c'
  brandStrength: 0.759206
  lightness: 0.925732
  saturation: 0.503991
  rhythmicContrast: 0.947683
purpose:
  - name: null
    item: null
    url: null
