name: 'Ernie '
favicon: null
layout_spectrum: 0.780405
typography_spectrum: 0.307432
title: Shar Pei
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#701020'
    - '#C0B090'
    - '#982830'
    - '#000000'
  brandStrength: 0.759206
  lightness: 0.925732
  saturation: 0.503991
  rhythmicContrast: 0.947683
purpose:
  - name: null
    item: null
    url: null
