analytics: {}
color:
  brandColors:
    - '#E0D8D8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.286318
name: 'Ernie '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0
