analytics: {}
color:
  brandColors:
    - '#2c1f31'
    - '#b2926c'
    - '#604c45'
    - '#8e6b4b'
    - '#e9cd9c'
  brandStrength: 0.759206
  lightness: 0.925732
  rhythmicContrast: 0.947683
  saturation: 0.503991
cta: {}
layout_spectrum: 0
name: 'Ernie '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.307432
