name: 'Ernie '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#391c16'
    - '#e3d828'
    - '#dc4c0d'
    - '#b3b0bd'
    - '#b08920'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
